
version: 2

models:
  - name: calcul_aggregat
    description: "Calcul des aggregats par univers"
    columns:
      - name: univers_1
        description: "univers_1"
      - name: nb
        description: "nombre articles"  