
version: 2

sources:
  - name: public
    tables:
      - name: codification
      - name: calcul_aggregat

target:
  - name: public
    tables:
      - name: calcul_aggregat
      - name: calcul_aggmerge
