
version: 2

sources:
  - name: public
    tables:
      - name: sales
  - name: raw
    tables:
      - name: users

  - name: tcph_sf1
    database: snowflake_sample_data
    schema: tpch_sf1
    tables:
      - name: customer
      - name: lineitem
      - name: nation
      - name: orders
      - name: part
      - name: partsupp
      - name: region
      - name: supplier

target:
  - name: public
    tables:
      - name: agg_sales
